// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: classify.proto

package df_detect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoPath     string                 `protobuf:"bytes,1,opt,name=video_path,json=videoPath,proto3" json:"video_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_classify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_classify_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetVideoPath() string {
	if x != nil {
		return x.VideoPath
	}
	return ""
}

type ClassificationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFake        bool                   `protobuf:"varint,1,opt,name=is_fake,json=isFake,proto3" json:"is_fake,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationResult) Reset() {
	*x = ClassificationResult{}
	mi := &file_classify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationResult) ProtoMessage() {}

func (x *ClassificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_classify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationResult.ProtoReflect.Descriptor instead.
func (*ClassificationResult) Descriptor() ([]byte, []int) {
	return file_classify_proto_rawDescGZIP(), []int{1}
}

func (x *ClassificationResult) GetIsFake() bool {
	if x != nil {
		return x.IsFake
	}
	return false
}

func (x *ClassificationResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_classify_proto protoreflect.FileDescriptor

const file_classify_proto_rawDesc = "" +
	"\n" +
	"\x0eclassify.proto\x12\fdf_detection\"0\n" +
	"\x0fClassifyRequest\x12\x1d\n" +
	"\n" +
	"video_path\x18\x01 \x01(\tR\tvideoPath\"O\n" +
	"\x14ClassificationResult\x12\x17\n" +
	"\ais_fake\x18\x01 \x01(\bR\x06isFake\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence2`\n" +
	"\bClassify\x12T\n" +
	"\rClassifyVideo\x12\x1d.df_detection.ClassifyRequest\x1a\".df_detection.ClassificationResult\"\x00B@Z>github.com/Lalit-h2/DF-Detector/backend/main_service/df_detectb\x06proto3"

var (
	file_classify_proto_rawDescOnce sync.Once
	file_classify_proto_rawDescData []byte
)

func file_classify_proto_rawDescGZIP() []byte {
	file_classify_proto_rawDescOnce.Do(func() {
		file_classify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_classify_proto_rawDesc), len(file_classify_proto_rawDesc)))
	})
	return file_classify_proto_rawDescData
}

var file_classify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_classify_proto_goTypes = []any{
	(*ClassifyRequest)(nil),      // 0: df_detection.ClassifyRequest
	(*ClassificationResult)(nil), // 1: df_detection.ClassificationResult
}
var file_classify_proto_depIdxs = []int32{
	0, // 0: df_detection.Classify.ClassifyVideo:input_type -> df_detection.ClassifyRequest
	1, // 1: df_detection.Classify.ClassifyVideo:output_type -> df_detection.ClassificationResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_classify_proto_init() }
func file_classify_proto_init() {
	if File_classify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_classify_proto_rawDesc), len(file_classify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_classify_proto_goTypes,
		DependencyIndexes: file_classify_proto_depIdxs,
		MessageInfos:      file_classify_proto_msgTypes,
	}.Build()
	File_classify_proto = out.File
	file_classify_proto_goTypes = nil
	file_classify_proto_depIdxs = nil
}
