// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: classify.proto

package df_detect

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Classify_ClassifyVideo_FullMethodName = "/df_detection.Classify/ClassifyVideo"
)

// ClassifyClient is the client API for Classify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClassifyClient interface {
	ClassifyVideo(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassificationResult, error)
}

type classifyClient struct {
	cc grpc.ClientConnInterface
}

func NewClassifyClient(cc grpc.ClientConnInterface) ClassifyClient {
	return &classifyClient{cc}
}

func (c *classifyClient) ClassifyVideo(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassificationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassificationResult)
	err := c.cc.Invoke(ctx, Classify_ClassifyVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassifyServer is the server API for Classify service.
// All implementations must embed UnimplementedClassifyServer
// for forward compatibility.
type ClassifyServer interface {
	ClassifyVideo(context.Context, *ClassifyRequest) (*ClassificationResult, error)
	mustEmbedUnimplementedClassifyServer()
}

// UnimplementedClassifyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClassifyServer struct{}

func (UnimplementedClassifyServer) ClassifyVideo(context.Context, *ClassifyRequest) (*ClassificationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ClassifyVideo not implemented")
}
func (UnimplementedClassifyServer) mustEmbedUnimplementedClassifyServer() {}
func (UnimplementedClassifyServer) testEmbeddedByValue()                  {}

// UnsafeClassifyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassifyServer will
// result in compilation errors.
type UnsafeClassifyServer interface {
	mustEmbedUnimplementedClassifyServer()
}

func RegisterClassifyServer(s grpc.ServiceRegistrar, srv ClassifyServer) {
	// If the following call panics, it indicates UnimplementedClassifyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Classify_ServiceDesc, srv)
}

func _Classify_ClassifyVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifyServer).ClassifyVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Classify_ClassifyVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifyServer).ClassifyVideo(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Classify_ServiceDesc is the grpc.ServiceDesc for Classify service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Classify_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "df_detection.Classify",
	HandlerType: (*ClassifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClassifyVideo",
			Handler:    _Classify_ClassifyVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classify.proto",
}
