# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63lassify.proto\x12\x0c\x64\x66_detection\"%\n\x0f\x43lassifyRequest\x12\x12\n\nvideo_path\x18\x01 \x01(\t\";\n\x14\x43lassificationResult\x12\x0f\n\x07is_fake\x18\x01 \x01(\x08\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32`\n\x08\x43lassify\x12T\n\rClassifyVideo\x12\x1d.df_detection.ClassifyRequest\x1a\".df_detection.ClassificationResult\"\x00\x42@Z>github.com/Lalit-h2/DF-Detector/backend/main_service/df_detectb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z>github.com/Lalit-h2/DF-Detector/backend/main_service/df_detect'
  _CLASSIFYREQUEST._serialized_start=32
  _CLASSIFYREQUEST._serialized_end=69
  _CLASSIFICATIONRESULT._serialized_start=71
  _CLASSIFICATIONRESULT._serialized_end=130
  _CLASSIFY._serialized_start=132
  _CLASSIFY._serialized_end=228
# @@protoc_insertion_point(module_scope)
