# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import df_detect.classify_pb2 as classify__pb2


class ClassifyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyVideo = channel.unary_unary(
                '/df_detection.Classify/ClassifyVideo',
                request_serializer=classify__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=classify__pb2.ClassificationResult.FromString,
                )


class ClassifyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClassifyVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassifyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyVideo,
                    request_deserializer=classify__pb2.ClassifyRequest.FromString,
                    response_serializer=classify__pb2.ClassificationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'df_detection.Classify', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Classify(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClassifyVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/df_detection.Classify/ClassifyVideo',
            classify__pb2.ClassifyRequest.SerializeToString,
            classify__pb2.ClassificationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
